services:
  wmata-bus-positions:
    container_name: wmata-bus-positions-python
    tty: true
    environment:
      CONFIG_SECRETS_FILE: /run/secrets/config_secrets
      PYTHONUNBUFFERED: 1
    image: wmata-bus-positions-python
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure:3
    secrets:
      - config_secrets
secrets:
  config_secrets:
    file: ./config/.secrets.toml
