services:
  wmata-bus-positions:
    image: wmata-bus-positions-python
    tty: true
    environment:
      CONFIG_SECRETS_FILE: /run/secrets/config_secrets
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    secrets:
      - config_secrets
secrets:
  config_secrets:
    file: ./config/.secrets.toml
