---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wmata-bus-positions
  namespace: default
  labels:
    app: wmata-bus-positions
spec:
  selector:
    matchLabels:
      app: wmata-bus-positions
  replicas: 1
  template:
    metadata:
      labels:
        app: wmata-bus-positions
    spec:
      containers:
        - name: wmata-bus-positions
          image: wmata-bus-positions-python
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1000m"